apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: waaecommerceregistry.azurecr.io/users-microservice:__TAG__
          ports:
            - containerPort: 9090
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: eCommerceUserDB
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin
